<a href="https://colab.research.google.com/github/MScaramuzzi/A1-RNNs-for-Sequence-Labeling/blob/test-1/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Download the corpora and split it in training and test sets, structuring a dataframe.

In [ ]:
import urllib.request  #  download files
import tarfile  #  unzip files
import shutil
import os
import urllib.request  #  download files
import zipfile  #  unzip files

**Splits**: documents 1-100 are the train set, 101-150 validation set, 151-199 test set.

**Splitting**: you can decide to split documents into sentences or not, the choice is yours.

**I/O structure**: The input data will have three dimensions: 1-documents/sentences, 2-token, 3-features; for the output there are 2 possibilities: if you use one-hot encoding it will be 1-documents/sentences, 2-token labels, 3-classes, if you use a single integer that indicates the number of the class it will be 1-documents/sentences, 2-token labels.

In [ ]:
dataset_folder = os.path.join(os.getcwd(), "Dataset")

if not os.path.exists(dataset_folder):
    os.makedirs(dataset_folder)

url = "https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/dependency_treebank.zip"

dataset_path = os.path.join(dataset_folder, "dependency_treebank.zip")

if not os.path.exists(dataset_path):
    urllib.request.urlretrieve(url, dataset_path)
    print("Successful download")

with zipfile.ZipFile(dataset_path,"r") as zip_ref:
    zip_ref.extractall("Dataset")

print("Successful extraction")

Successful download
Successful extraction

In [ ]:
data_folder=os.getcwd()+"/Dataset/dependency_treebank/"

In [ ]:
# Just needed in case you'd like to append it to an array
data = []

for filename in os.listdir(data_folder):
    if filename.endswith("dp"): 
        data.append(filename)

Cicla su una frase
- Fintanto che non sei arrivato ad un punto seguito da uno spazio:
    * Leggi tutti i caratteri di una parola fino a che non trovi un spazio
    * Salta a riga dopo e ripeti

1. Trova indice righe splittate in train
2. Trova indice righe splittate in test
3. Trova indice righe splittate in validation

Commento

In [ ]:
sentences = []
words = []
unique_tags_train = []
unique_tags_test = []
unique_tags_val = []
tags = []
tag2 = []
file_len = []
cnt_sents = 0
docs = sorted(os.listdir(data_folder))
for filename in docs:
    if filename.endswith(".dp"): 
        with open(os.path.join(data_folder, filename), mode='r', encoding='utf-8') as text:
                for i,line in enumerate(text):
                    if len(line.split())>0:
                        word, tag, _ = line.split("\t")    # prova a inventare un altro modo split
                        words.append(word)
                        tags.append(tag)
                        if tag not in unique_tags_train:
                            unique_tags_train.append(tag)
                        if word == ".": # condizione fine frase
                            sentences.append(words[:i])
                            cnt_sents+=1
                            tag2.append(tags[:i])
                            words = []
                            tags =[]
                file_len.append(cnt_sents)
        cnt_sents = 0

In [ ]:
len(unique_tags)

45

In [ ]:
unique_tags

['NNP',
 ',',
 'CD',
 'NNS',
 'JJ',
 'MD',
 'VB',
 'DT',
 'NN',
 'IN',
 '.',
 'VBZ',
 'VBG',
 'CC',
 'VBD',
 'VBN',
 'RB',
 'TO',
 'PRP',
 'RBR',
 'WDT',
 'VBP',
 'RP',
 'PRP$',
 'JJS',
 'POS',
 '``',
 'EX',
 "''",
 'WP',
 ':',
 'JJR',
 'WRB',
 '$',
 'NNPS',
 'WP$',
 '-LRB-',
 '-RRB-',
 'PDT',
 'RBS',
 'FW',
 'UH',
 'SYM',
 'LS',
 '#']

* Trova lunghezza righe documento
* a ultima sentence aggiungi un marker per indicare che Ã¨ end of file 
* fino a quella sentence saranno doc = nome doc

In [ ]:
file_len[:5]

[2, 1, 30, 17, 3]

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# create single dataframe row
dataframe_rows = {
#    'docs': [doc for doc in docs],
    'sentences': sentences,
    'tags': tag2,
    "docs": np.repeat(docs, file_len)
}

In [ ]:
df = pd.DataFrame(dataframe_rows)
df.head(10)

,sentences,tags,docs
0,"[Pierre, Vinken, ,, 61, years, old, ,, will, j...","[NNP, NNP, ,, CD, NNS, JJ, ,, MD, VB, DT, NN, ...",wsj_0001.dp
1,"[Mr., Vinken, is, chairman, of, Elsevier, N.V....","[NNP, NNP, VBZ, NN, IN, NNP, NNP, ,, DT, NNP, ...",wsj_0001.dp
2,"[Rudolph, Agnew, ,, 55, years, old, and, forme...","[NNP, NNP, ,, CD, NNS, JJ, CC, JJ, NN, IN, NNP...",wsj_0002.dp
3,"[A, form, of, asbestos, once, used, to, make, ...","[DT, NN, IN, NN, RB, VBN, TO, VB, NNP, NN, NNS...",wsj_0003.dp
4,"[The, asbestos, fiber, ,, crocidolite, ,, is, ...","[DT, NN, NN, ,, NN, ,, VBZ, RB, JJ, IN, PRP, V...",wsj_0003.dp
5,"[Lorillard, Inc., ,, the, unit, of, New, York-...","[NNP, NNP, ,, DT, NN, IN, JJ, JJ, NNP, NNP, WD...",wsj_0003.dp
6,"[Although, preliminary, findings, were, report...","[IN, JJ, NNS, VBD, VBN, RBR, IN, DT, NN, IN, ,...",wsj_0003.dp
7,"[A, Lorillard, spokewoman, said, ,, ``, This, ...","[DT, NNP, NN, VBD, ,, ``, DT, VBZ, DT, JJ, NN, .]",wsj_0003.dp
8,"[We, 're, talking, about, years, ago, before, ...","[PRP, VBP, VBG, IN, NNS, IN, IN, NN, VBD, IN, ...",wsj_0003.dp
9,"[There, is, no, asbestos, in, our, products, n...","[EX, VBZ, DT, NN, IN, PRP$, NNS, RB, .]",wsj_0003.dp

In [ ]:
df.loc[df['docs'] == 'wsj_0101.dp']
# train tutti quelli prima dell'index
#

,sentences,tags,docs
1936,"[A, House-Senate, conference, approved, major,...","[DT, NNP, NN, VBD, JJ, NNS, IN, DT, NN, IN, JJ...",wsj_0101.dp
1937,"[For, the, Agency, for, International, Develop...","[IN, DT, NNP, IN, NNP, NNP, ,, NNS, VBD, $, CD...",wsj_0101.dp
1938,"[The, conference, approved, at, least, $, 55, ...","[DT, NN, VBD, IN, JJS, $, CD, CD, IN, JJ, NN, ...",wsj_0101.dp
1939,"[The, agreement, on, Poland, contrasts, with, ...","[DT, NN, IN, NNP, VBZ, IN, DT, JJ, NNS, VBG, I...",wsj_0101.dp
1940,"[These, fiscal, pressures, are, also, a, facto...","[DT, JJ, NNS, VBP, RB, DT, NN, IN, VBG, DT, NN...",wsj_0101.dp
1941,"[To, accommodate, the, additional, cash, assis...","[TO, VB, DT, JJ, NN, NN, ,, DT, NNP, NNPS, NNP...",wsj_0101.dp
1942,"[And, though, the, size, of, the, loan, guaran...","[CC, IN, DT, NN, IN, DT, NN, NNS, VBN, NN, VBZ...",wsj_0101.dp
1943,"[The, action, on, Poland, came, as, the, confe...","[DT, NN, IN, NNP, VBD, IN, DT, NN, RB, VBD, $,...",wsj_0101.dp
1944,"[The, House, and, Senate, are, divided, over, ...","[DT, NNP, CC, NNP, VBP, VBN, IN, IN, DT, NNP, ...",wsj_0101.dp
1945,"[In, a, second, area, of, common, concern, ,, ...","[IN, DT, JJ, NN, IN, JJ, NN, ,, DT, NN, NN, ,,...",wsj_0101.dp
1946,"[The, sweeping, nature, of, the, bill, draws, ...","[DT, JJ, NN, IN, DT, NN, VBZ, DT, NN, IN, JJ, ...",wsj_0101.dp
1947,"[Panama, was, stripped, of, this, right, becau...","[NNP, VBD, VBN, IN, DT, NN, IN, IN, NNP, NNS, ...",wsj_0101.dp
1948,"[About, a, quarter, of, this, share, has, alre...","[IN, DT, NN, IN, DT, NN, VBZ, RB, VBN, VBN, ,,...",wsj_0101.dp
1949,"[The, potential, sales, are, nearly, $, 9.3, m...","[DT, JJ, NNS, VBP, RB, $, CD, CD, ,, CC, NNP, ...",wsj_0101.dp
1950,"[-RRB-, began, the, bidding, this, year, by, p...","[-RRB-, VBD, DT, NN, DT, NN, IN, VBG, NN, IN, ...",wsj_0101.dp
1951,"[Rep., Jerry, Lewis, ,, a, conservative, Calif...","[NNP, NNP, NNP, ,, DT, JJ, NN, ,, VBD, DT, NN,...",wsj_0101.dp
1952,"[Jamaica, ,, wary, of, upsetting, its, Caribbe...","[NNP, ,, JJ, IN, VBG, PRP$, NNP, NNP, NNS, ,, ...",wsj_0101.dp
1953,"[In, separate, floor, action, ,, the, House, w...","[IN, JJ, NN, NN, ,, DT, NNP, VBD, NN, NNS, CC,...",wsj_0101.dp
1954,"[The, funding, is, attached, to, an, estimated...","[DT, NN, VBZ, VBN, TO, DT, VBN, $, CD, CD, NN,...",wsj_0101.dp
1955,"[The, leadership, hopes, to, move, the, compro...","[DT, NN, VBZ, TO, VB, DT, NN, NN, RB, TO, DT, ...",wsj_0101.dp
1956,"[The, most, recent, example, was, a, nearly, $...","[DT, RBS, JJ, NN, VBD, DT, RB, $, CD, CD, JJ, ...",wsj_0101.dp
1957,"[And, after, losing, a, battle, Tuesday, night...","[CC, IN, VBG, DT, NN, NNP, NN, IN, DT, NNP, NN...",wsj_0101.dp

In [ ]:
print('Dataset Info:')
print(df.info(),'\n')

print('Dataset Head:')
display(df.head())

print('\nDataset Description:')
display(df.describe())

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3828 entries, 0 to 3827
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sentences  3828 non-null   object
 1   tags       3828 non-null   object
 2   docs       3828 non-null   object
dtypes: object(3)
memory usage: 89.8+ KB
None

Dataset Head:

,sentences,tags,docs
0,"[Pierre, Vinken, ,, 61, years, old, ,, will, j...","[NNP, NNP, ,, CD, NNS, JJ, ,, MD, VB, DT, NN, ...",wsj_0001.dp
1,"[Mr., Vinken, is, chairman, of, Elsevier, N.V....","[NNP, NNP, VBZ, NN, IN, NNP, NNP, ,, DT, NNP, ...",wsj_0001.dp
2,"[Rudolph, Agnew, ,, 55, years, old, and, forme...","[NNP, NNP, ,, CD, NNS, JJ, CC, JJ, NN, IN, NNP...",wsj_0002.dp
3,"[A, form, of, asbestos, once, used, to, make, ...","[DT, NN, IN, NN, RB, VBN, TO, VB, NNP, NN, NNS...",wsj_0003.dp
4,"[The, asbestos, fiber, ,, crocidolite, ,, is, ...","[DT, NN, NN, ,, NN, ,, VBZ, RB, JJ, IN, PRP, V...",wsj_0003.dp

Dataset Description:

                               sentences                    tags         docs
count                               3828                    3828         3828
unique                              3819                    3795          199
top     [Terms, were, n't, disclosed, .]  [NNS, VBD, RB, VBN, .]  wsj_0118.dp
freq                                   8                       8          172